version: '3.9'

services:
  base:
    build:
      context: ./
      dockerfile: ./docker/base/Dockerfile
    image: app-base
  app:
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
    image: app-dev
    volumes:
      - .:/home/app
    networks:
      - default
  db:
    image: postgres:15.1
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: app
#    ports:
#      - "5430:5432"
    networks:
      - default
    volumes:
      - app-db:/var/lib/postgresql/data:rw
  web:
    image: nginx:1.22.0
    volumes:
      - .:/home/app
      - ./docker/dev/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    ports:
      - 80:80

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  app-db:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
