version: '3.9'

services:
  base:
    build:
      context: ./
      dockerfile: ./docker/base/Dockerfile
    image: app-base
  app:
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
    image: app-dev
    volumes:
      - .:/home/app
    networks:
      - default
  web:
    image: nginx:1.22.0
    volumes:
      - .:/home/app
      - ./docker/dev/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    ports:
      - 80:80
