version: '3.9'

services:
  base:
    build:
      context: ./
      dockerfile: ./docker/base/Dockerfile
    image: app-base
  app:
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
    image: app-dev
    volumes:
      - .:/home/app
    networks:
      - default
  db:
    image: postgres:15.1
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: app
    ports:
      - "5432:5432"
    networks:
      - default
    volumes:
      - app-db:/var/lib/postgresql/data:rw
  web:
    image: nginx:1.22.0
    volumes:
      - .:/home/app
      - ./docker/dev/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    ports:
      - 80:80

volumes:
  app-db:
